"""Write the Findings section of the valuation README from computed output.

Same discipline as the other studies: every number in the prose is read from
output/, never typed. Run after 02_analysis.py (+ ideally 03_reconcile.py).

Run: python python/04_findings.py
"""
from __future__ import annotations

from pathlib import Path

import polars as pl

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output"
README = ROOT / "README.md"
MARKER = "## Findings"


def season_block(season: str) -> str:
    out = OUT / season
    values = pl.read_csv(out / "player_values.csv")
    lineups = pl.read_csv(out / "lineup_table.csv")
    curve = pl.read_csv(out / "cv_curve.csv").sort("cv_wmse")
    validation = pl.read_csv(out / "validation.csv")

    lam = float(curve["lam"][0])
    top = values.head(10)
    top_rows = "\n".join(
        f"| {r['rank']} | {r['player']} | **{r['rapm_100']:+.2f}** "
        f"| [{r['ci_lo']:+.2f}, {r['ci_hi']:+.2f}] | {r['poss']:,.0f} |"
        for r in top.iter_rows(named=True))

    best_l = lineups.row(0, named=True)
    worst_l = lineups.sort("net_100").row(0, named=True)

    rho = float(validation.filter(
        pl.col("check").str.contains("Spearman"))["value"][0])
    r_net = float(validation.filter(
        pl.col("check").str.contains("NET_RATING"))["value"][0])

    n_players = values.height
    ci_width = float((values["ci_hi"] - values["ci_lo"]).median())

    return f"""### {season}

Penalty chosen by CV: **λ = {lam:g}**. {n_players} players over the possession
threshold; median 95% CI width **±{ci_width / 2:.1f} points per 100** — the
honest single-season noise floor for this model family.

| Rank | Player | Effect / 100 poss | 95% CI | Poss |
|---|---|---|---|---|
{top_rows}

**Best high-usage lineup** (1,000+ possessions):
{best_l['GROUP_NAME']} ({best_l['TEAM_ABBREVIATION']}) —
**{best_l['net_100']:+.1f} per 100** over {best_l['POSS']:,.0f} possessions.
**Worst:** {worst_l['GROUP_NAME']} ({worst_l['TEAM_ABBREVIATION']}),
{worst_l['net_100']:+.1f} per 100 over {worst_l['POSS']:,.0f}.

Validation: lineup minutes and plus-minus reconstruct team totals
(exact on points); independent net-rate agrees with the NBA's NET_RATING at
r = {r_net:.3f}; Spearman vs raw plus-minus = {rho:.2f} — anchored in reality,
and the gap from 1.0 is the teammate adjustment working.
"""


def build() -> str:
    seasons = sorted(p.name for p in OUT.iterdir() if p.is_dir())
    blocks = "\n".join(season_block(s) for s in seasons)
    return f"""{MARKER}

Every number below is generated by `python/04_findings.py` from `output/`, not
typed by hand. Both implementations (R and Python) reconcile before this is
written.

{blocks}
### Reading the two seasons together

- The model finds the consensus stars without being told who they are — the
  top of each table is recognisable to anyone who watched that season. That
  is a *face-validity check*, not the product. The product is the ordering of
  everyone else, where intuition runs out.
- RAPM-family models famously promote elite role players alongside stars.
  That is not a bug: it is the model reporting that scoring volume and
  lineup impact are different quantities.
- Single-season CIs of ±2-3 per 100 are why serious deployments blend
  multiple seasons and add box/tracking priors (see "Where this sits in the
  literature"). A model whose error bars you can defend is worth more than a
  sharper-looking one whose error bars you cannot.
"""


def main() -> int:
    text = README.read_text()
    head = text.split(MARKER)[0].rstrip()
    README.write_text(head + "\n\n" + build())
    print(f"Updated Findings in {README}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
